# my global config
global:
  scrape_interval: 15s # Set the scape interval to 15 seconds; the default is 1 minute
  evaluation_interval: 15s # Evaluate rules every 15 seconds
  #Scrape time out is set to default (10 seconds)

# Load rules once and periodically evaluate according to the global 'evaluation_interval'
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.0:9090']
  - job_name: 'spring-actuator'
    metrics_path: /actuator/prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.56.1:8080']